# Generated by Django 4.1.7 on 2023-02-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electronic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='electronic/')),
                ('flag', models.CharField(choices=[('France', 'France'), ('Englang', 'Englang')], max_length=20, verbose_name='flag')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fashion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='fashion/')),
                ('flag', models.CharField(choices=[('France', 'France'), ('Englang', 'Englang')], max_length=20, verbose_name='flag')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jewellery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('price', models.FloatField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='shoping/')),
                ('flag', models.CharField(choices=[('France', 'France'), ('Englang', 'Englang')], max_length=20, verbose_name='flag')),
                ('description', models.TextField(max_length=200, verbose_name='description')),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
